name: Qodana

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      test_artifact_name:
        required: false
        type: string
        default: test-results
      coverage_artifact_name:
        required: false
        type: string
        default: test-coverage
    secrets:
      QODANA_TOKEN:
        required: true

defaults:
  run:
    working-directory: ./

jobs:
  qodana-check:
    runs-on: ubuntu-latest
    name: Inspect Code

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref }}

      - name: Download Test Reports Artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: ${{ inputs.test_artifact_name }}
          path: ./qodana-downloaded-reports/test-results

      - name: Download Coverage Report Artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: ${{ inputs.coverage_artifact_name }}
          path: ./.qodana/code-coverage

      - name: Run Qodana
        uses: JetBrains/qodana-action@f5aa2889b113c16bd6aee47817b027537ee33ac7 # v2025.1
        with:
          args: --baseline,.qodana/qodana.sarif.json
          push-fixes: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
